apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __APP_NAME__-dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: __APP_NAME__
        updateTimestamp: "__TIMESTAMP__"
    spec:
      containers:
      - name: __APP_NAME__-ctr
        image: >-
          __IMAGE__
        imagePullPolicy: Always
        ports:
        - name: httpport
          containerPort: 8080
        env:
          - name: API_ENDPOINT
            value: "http://127.0.0.1:8082/"
          - name: DEPLOY_TIMESTAMP
            value: "__TIMESTAMP__"


